### ISSUE TITLE
1.12 - /nbti tocommand generates invalid JSON

### ISSUE THREAD

**Issue by 14ercooper** [goncalomb/NBTEditor#10]
The /nbti tocommand command generates JSON that is invalid and will not work in command blocks.
The Numerical tags in lists (enchants, lore, attribute modifiers) are not supposed to be there
    0:               1:              2:           etc.
Numbers should not have the data type specified after the number (s, L, b, etc.); found in enchants, UUIDs, and the like.

**Comment by goncalomb** [comment]
It should be fixed now, please report any other problems. Thanks.
