### ISSUE TITLE
The 1.8 version is not working.

### ISSUE THREAD

**Issue by ghost** [goncalomb/NBTEditor#15]
If I type in: "/help NBTEditor" it's showing me:
" ---- Help: NBTEditor -- Page 1/1 ----
Commands from NBTEditor:"
And I've also tried to use commands such as "/bookofsouls get pig" but nothing was happening... It was just showing up "Unknown command. Type "/help" for help. It may be just on version 1.8.9 but i cant swap the version right now...

**Comment by goncalomb** [comment]
These older versions are not supported anymore. You need to update to a newer version.
