### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by PoorBoyDaniel** [goncalomb/NBTEditor#16]
When I double click on the jar exe file it doesn't open, it does absolutely nothing. Other jar exe files work fine, and I've searched for a solution for hours, to no avail.

**Comment by goncalomb** [comment]
Apologies for super late response. The NBTEditor is a plugin for CraftBukkit/Spigot, you cannot run it as a normal Java program. [More information on BukkiDev](https://dev.bukkit.org/projects/nbteditor).
