### ISSUE TITLE
Suggestion: Potion + Arrow Colors

### ISSUE THREAD

**Issue by Lovyxia** [goncalomb/NBTEditor#19]
I'd love to see the ability to change potion and arrow colors for custom potions & arrows.
Minecraft supports it.

It'd be much more comfortable changing colors with this plugin than using external tools like http://minecraft.tools/en/potion.php

It's something no Spigot/Bukkit plugin seems to have done yet as well.

That's all. This plugin has been a staple for my server for years. The 3.0 update was great.

**Comment by goncalomb** [comment]
Interesting, I didn’t know about that! I'll definitely add it.

**Comment by goncalomb** [comment]
Done. Should already be on the [latest build on Jenkins](https://jenkins.androkai.net/job/NBTEditor/). New `CustomPotionColor` variable for potion items and tipped arrows (`/nbti`) and new `Color` variable for arrow entities (`/bos`). Thanks for the tip.

**Comment by Lovyxia** [comment]
Thank you so much for the amazingly quick response! As I said, I love the plugin. Can't imagine living without it anymore! <3
