### ISSUE TITLE
Suggestion: Change Data Value (Damage etc)

### ISSUE THREAD

**Issue by Lovyxia** [goncalomb/NBTEditor#21]
It'd be great if we could change data values, especially item damage values.

I'm using this plugin on my server in conjunction with a resource pack to make custom items and it would be very useful to retroactively change the damage value of tools (including having them reach negative "durabilites").

**Comment by goncalomb** [comment]
Thanks for the tip. I added the Damage variable (with no limits) for items. Download the [latest build on Jenkins](https://jenkins.androkai.net/job/NBTEditor/) (Minecraft 1.13).

**Comment by Lovyxia** [comment]
No 1.12.2 backwards compatibility? We're not upgrading until spigot and all our plugins are ready :s

**Comment by goncalomb** [comment]
Sorry, no. Many things changed in 1.13 making it incompatible with 1.12, and normally I don't update old versions. If I see that people are holding back on updating to 1.13 I may consider develop a 1.12 version in parallel. I'm also short on time on the next few weeks, so don't expect many updates, sorry.

**Comment by Lovyxia** [comment]
Alright, I plan on updating in the future anyways. It just seems like Spigot isn't ready for an upgrade yet, judging from the news on the main page.
