### ISSUE TITLE
Option to customize or remove 'done' debug messaging.

### ISSUE THREAD

**Issue by mibby** [goncalomb/NBTEditor#28]
Noticed this line occurring in console every time someone made a purchase in my in-game shop that gave them itemstorage items from console.
https://github.com/goncalomb/NBTEditor/blob/63c5a43e973713f1a3ba0a984014eaafda016900/src/main/java/com/goncalomb/bukkit/nbteditor/commands/CommandItemStorage.java#L84

Would it be possible to make this message customizable so it can be edited or removed?

**Comment by goncalomb** [comment]
The messages do need some cleanup. Maybe I can work on implementing a config to disable confirmation messages to the console, only showing errors and warnings.

**Comment by mibby** [comment]
I'd appreciate it! :)

**Comment by goncalomb** [comment]
I choose not to add a config, because this would be the only use case for it. But I removed the message if the sender is the console. There's also a new command /is open, if you want to try.
