### ISSUE TITLE
please fix bug not add lore show item.

### ISSUE THREAD

**Issue by vanthoi** [goncalomb/NBTEditor#3]
i user Nbteditor 2.01 . MC spigot 1.10.2 build 7/1/2016 at 13h 
i user nbtitem lore add content not show item.
I stop server start server item still show lore added!

**Comment by goncalomb** [comment]
I'm not sure I understand what is the bug that you are experiencing.

I tried editing some items on 1.10 with `/nbtitem lore add` and `/nbtitem name`, sometimes it would not immediately update the item. After changing the item to another inventory slot or dropping the item, it shows the correct values.
