### ISSUE TITLE
Tags:[""] supported, but not in BoS

### ISSUE THREAD

**Issue by Taybosquee** [goncalomb/NBTEditor#4]
I don't know if this is considered a feature request or a bug but... Yea. Tags on entities are saved in Book of Souls(s), but they aren't listed inside the book with the other information about the entity.
Note; if you do by change fix/add this feature, I'd highly advise adding it to its own book page if possible. I've seen some people use a lot of tags on an entity before and/or very long strings.

Thanks again for making the awesome plugin, and I hope it's around for a long time to come. :D

**Comment by goncalomb** [comment]
I assume you are talking about using a Empty BoS on a existing entity. Yes, you are right, it will capture and store all the information (including 'Tags'), even though some tags may not exist as "variables" and are not displayed on the visible part of the book (and cannot be changed or removed). This is not ideal, but I never really "fixed it". It will probably be "fixed"/changed when I get round to work on improving the variable system.

Thanks for reminding me of this. I'm glad you like the NBTEditor.

**Comment by Taybosquee** [comment]
I love it! I have a whole library dedicated to double chests of saved BoS'. lol Anyways, yes. That was what I meant, and thanks for the reply. :)

**Comment by Combustible** [comment]
#26 Added pull request to make Tags accessible with `/bos`
