### ISSUE TITLE
Jenkins isn't available

### ISSUE THREAD

**Issue by enterih** [goncalomb/NBTEditor#40]
Just to let you know about to fix it

**Comment by Combustible** [comment]
Looks like he set it up so you can get packages directly from github - https://github.com/goncalomb/NBTEditor/packages

**Comment by goncalomb** [comment]
Yes, I did some tests with GitHub Packages but I decided to host my own Jenkins instance.
New builds will be stored there, 1.15 compatible builds will be available soon...
https://jenkins.goncalomb.com/job/NBTEditor/
