### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by enterih** [goncalomb/NBTEditor#50]
First issue to report,that the plugin dont work on 1.16.X

https://pastebin.com/GcvG6YSx

**Comment by mibby** [comment]
@Combustible Do you think it would be possible for you to PR a quick migration to 1.16?

**Comment by Combustible** [comment]
Sorry it took so long - #51. There's a link there you can download a working temporary version.

**Comment by goncalomb** [comment]
#51 merged. Due to the big changes in 1.16, I'm bumping the NBTEditor version to 3.3.
New contributions should go to the mc-1.16 branch.
There's already a build on https://jenkins.goncalomb.com/job/NBTEditor/.
Thanks Again.
